package ConcatModule;


/**
* ConcatModule/ConcatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcatModule.idl
* Sunday, May 28, 2023 3:08:37 PM IST
*/

public interface ConcatOperations 
{
  String concat_string (String str1, String str2);
} // interface ConcatOperations
