package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorModule.idl
* Sunday, May 28, 2023 11:31:30 AM IST
*/

public interface CalculatorOperations 
{
  float add (float num1, float num2);
  float sub (float num1, float num2);
  float mult (float num1, float num2);
  float div (float num1, float num2);
} // interface CalculatorOperations
